<a href="https://colab.research.google.com/github/amitthakur2013/play_with_pandas/blob/master/2-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
df=pd.read_csv('http://samplecsvs.s3.amazonaws.com/Sacramentorealestatetransactions.csv')
df.head()

             street        city    zip  ...  price   latitude   longitude
0      3526 HIGH ST  SACRAMENTO  95838  ...  59222  38.631913 -121.434879
1       51 OMAHA CT  SACRAMENTO  95823  ...  68212  38.478902 -121.431028
2    2796 BRANCH ST  SACRAMENTO  95815  ...  68880  38.618305 -121.443839
3  2805 JANETTE WAY  SACRAMENTO  95815  ...  69307  38.616835 -121.439146
4   6001 MCMAHON DR  SACRAMENTO  95824  ...  81900  38.519470 -121.435768

[5 rows x 12 columns]

In [0]:
df1=df[df['price']>81000]
df1.head()

                            street            city  ...   latitude   longitude
4                  6001 MCMAHON DR      SACRAMENTO  ...  38.519470 -121.435768
5               5828 PEPPERMILL CT      SACRAMENTO  ...  38.662595 -121.327813
6              6048 OGDEN NASH WAY      SACRAMENTO  ...  38.681659 -121.351705
7                    2561 19TH AVE      SACRAMENTO  ...  38.535092 -121.481367
8  11150 TRINITY RIVER DR Unit 114  RANCHO CORDOVA  ...  38.621188 -121.270555

[5 rows x 12 columns]

In [0]:
df['price'].max()

884790

In [0]:
df2=df[df['type']=='Residential']
df2.head()

             street        city    zip  ...  price   latitude   longitude
0      3526 HIGH ST  SACRAMENTO  95838  ...  59222  38.631913 -121.434879
1       51 OMAHA CT  SACRAMENTO  95823  ...  68212  38.478902 -121.431028
2    2796 BRANCH ST  SACRAMENTO  95815  ...  68880  38.618305 -121.443839
3  2805 JANETTE WAY  SACRAMENTO  95815  ...  69307  38.616835 -121.439146
4   6001 MCMAHON DR  SACRAMENTO  95824  ...  81900  38.519470 -121.435768

[5 rows x 12 columns]

In [0]:
df.fillna(0,inplace=True)

In [0]:
df.shape

(985, 12)

In [0]:
df.tail()

                  street             city    zip  ...   price   latitude   longitude
980   9169 GARLINGTON CT       SACRAMENTO  95829  ...  232425  38.457679 -121.359620
981      6932 RUSKUT WAY       SACRAMENTO  95823  ...  234000  38.499893 -121.458890
982    7933 DAFFODIL WAY   CITRUS HEIGHTS  95610  ...  235000  38.708824 -121.256803
983     8304 RED FOX WAY        ELK GROVE  95758  ...  235301  38.417000 -121.397424
984  3882 YELLOWSTONE LN  EL DORADO HILLS  95762  ...  235738  38.655245 -121.075915

[5 rows x 12 columns]

In [0]:
df[2:5]

             street        city    zip  ...  price   latitude   longitude
2    2796 BRANCH ST  SACRAMENTO  95815  ...  68880  38.618305 -121.443839
3  2805 JANETTE WAY  SACRAMENTO  95815  ...  69307  38.616835 -121.439146
4   6001 MCMAHON DR  SACRAMENTO  95824  ...  81900  38.519470 -121.435768

[3 rows x 12 columns]

In [0]:
df.zip

In [0]:
df3=df[['zip','state']]
df3[:5]

     zip state
0  95838    CA
1  95823    CA
2  95815    CA
3  95815    CA
4  95824    CA

In [0]:
df.zip.max()

95864

In [0]:
df.describe()

                zip        beds  ...    latitude   longitude
count    985.000000  985.000000  ...  985.000000  985.000000
mean   95750.697462    2.911675  ...   38.607732 -121.355982
std       85.176072    1.307932  ...    0.145433    0.138278
min    95603.000000    0.000000  ...   38.241514 -121.551704
25%    95660.000000    2.000000  ...   38.482717 -121.446127
50%    95762.000000    3.000000  ...   38.626582 -121.376220
75%    95828.000000    4.000000  ...   38.695589 -121.295778
max    95864.000000    8.000000  ...   39.020808 -120.597599

[8 rows x 7 columns]

In [0]:
df.index

RangeIndex(start=0, stop=985, step=1)

In [0]:
df.set_index('zip')

                                street             city  ...   latitude   longitude
zip                                                      ...
95838                     3526 HIGH ST       SACRAMENTO  ...  38.631913 -121.434879
95823                      51 OMAHA CT       SACRAMENTO  ...  38.478902 -121.431028
95815                   2796 BRANCH ST       SACRAMENTO  ...  38.618305 -121.443839
95815                 2805 JANETTE WAY       SACRAMENTO  ...  38.616835 -121.439146
95824                  6001 MCMAHON DR       SACRAMENTO  ...  38.519470 -121.435768
95841               5828 PEPPERMILL CT       SACRAMENTO  ...  38.662595 -121.327813
95842              6048 OGDEN NASH WAY       SACRAMENTO  ...  38.681659 -121.351705
95820                    2561 19TH AVE       SACRAMENTO  ...  38.535092 -121.481367
95670  11150 TRINITY RIVER DR Unit 114   RANCHO CORDOVA  ...  38.621188 -121.270555
95673                     7325 10TH ST        RIO LINDA  ...  38.700909 -121.442979
95838                 645 MORRISON AVE       SACRAMENTO  ...  38.637663 -121.451520
95823                    4085 FAWN CIR       SACRAMENTO  ...  38.470746 -121.458918
95815                  2930 LA ROSA RD       SACRAMENTO  ...  38.618698 -121.435833
95822                    2113 KIRK WAY       SACRAMENTO  ...  38.482215 -121.492603
95842              4533 LOCH HAVEN WAY       SACRAMENTO  ...  38.672914 -121.359340
95842                   7340 HAMDEN PL       SACRAMENTO  ...  38.700051 -121.351278
95673                      6715 6TH ST        RIO LINDA  ...  38.689591 -121.452239
95621          6236 LONGFORD DR Unit 1   CITRUS HEIGHTS  ...  38.679776 -121.314089
95833                  250 PERALTA AVE       SACRAMENTO  ...  38.612099 -121.469095
95673                  113 LEEWILL AVE        RIO LINDA  ...  38.689999 -121.463220
95621               6118 STONEHAND AVE   CITRUS HEIGHTS  ...  38.707851 -121.320707
95823                4882 BANDALIN WAY       SACRAMENTO  ...  38.468173 -121.444071
95660                  7511 OAKVALE CT  NORTH HIGHLANDS  ...  38.702792 -121.382210
95834                     9 PASTURE CT       SACRAMENTO  ...  38.628631 -121.488097
95660               3729 BAINBRIDGE DR  NORTH HIGHLANDS  ...  38.701499 -121.376220
95843               3828 BLACKFOOT WAY         ANTELOPE  ...  38.709740 -121.373770
95820                  4108 NORTON WAY       SACRAMENTO  ...  38.537526 -121.478315
95832                 1469 JANRICK AVE       SACRAMENTO  ...  38.476472 -121.501711
95827                    9861 CULP WAY       SACRAMENTO  ...  38.558423 -121.327948
95828            7825 CREEK VALLEY CIR       SACRAMENTO  ...  38.472122 -121.404199
...                                ...              ...  ...        ...         ...
95747                  2100 BEATTY WAY        ROSEVILLE  ...  38.737882 -121.308142
95660              6920 GILLINGHAM WAY  NORTH HIGHLANDS  ...  38.694279 -121.373395
95632                 82 WILDFLOWER DR             GALT  ...  38.259708 -121.311616
95624                  8652 BANTON CIR        ELK GROVE  ...  38.444000 -121.370993
95843              8428 MISTY PASS WAY         ANTELOPE  ...  38.722959 -121.347115
95828                7958 ROSEVIEW WAY       SACRAMENTO  ...  38.467836 -121.410366
95624                    9020 LUKEN CT        ELK GROVE  ...  38.451398 -121.366614
95828              7809 VALLECITOS WAY       SACRAMENTO  ...  38.508217 -121.411207
95610               8445 OLD AUBURN RD   CITRUS HEIGHTS  ...  38.715423 -121.246743
95757                  10085 ATKINS DR        ELK GROVE  ...  38.390893 -121.437821
95758              9185 CERROLINDA CIR        ELK GROVE  ...  38.424497 -121.426595
95678                 9197 CORTINA CIR        ROSEVILLE  ...  38.793152 -121.290025
95608                  5429 HESPER WAY       CARMICHAEL  ...  38.665104 -121.315901
95632                 1178 WARMWOOD CT             GALT  ...  38.289544 -121.284607
95842                    4900 ELUDE CT       SACRAMENTO  ...  38.696740 -121.350519
95834                    3557 SODA WAY       SACRAMENTO  ...  38.631026 -121.501879
95821             3528 SAINT GEORGE DR       SACRAMENTO  ...  38.629468 -121.376445
95660                7381 WASHBURN WAY  NORTH HIGHLANDS  ...  38.703550 -121.375103
95682             2181 WINTERHAVEN CIR     CAMERON PARK  ...  38.697570 -120.995739
95662                 7540 HICKORY AVE       ORANGEVALE  ...  38.703056 -121.235221
95757              5024 CHAMBERLIN CIR        ELK GROVE  ...  38.389756 -121.446246
95648                2400 INVERNESS DR          LINCOLN  ...  38.897814 -121.324691
95823                  5 BISHOPGATE CT       SACRAMENTO  ...  38.467936 -121.445477
95823                 5601 REXLEIGH DR       SACRAMENTO  ...  38.445342 -121.441504
95758                 1909 YARNELL WAY        ELK GROVE  ...  38.417382 -121.484325
95829               9169 GARLINGTON CT       SACRAMENTO  ...  38.457679 -121.359620
95823                  6932 RUSKUT WAY       SACRAMENTO  ...  38.499893 -121.458890
95610                7933 DAFFODIL WAY   CITRUS HEIGHTS  ...  38.708824 -121.256803
95758                 8304 RED FOX WAY        ELK GROVE  ...  38.417000 -121.397424
95762              3882 YELLOWSTONE LN  EL DORADO HILLS  ...  38.655245 -121.075915

[985 rows x 11 columns]

In [0]:
df.index

RangeIndex(start=0, stop=985, step=1)

In [0]:
df.reset_index(inplace=True)

In [0]:
df.index

RangeIndex(start=0, stop=985, step=1)

In [0]:
df.loc[2]

index                                   2
street                     2796 BRANCH ST
city                           SACRAMENTO
zip                                 95815
state                                  CA
beds                                    2
baths                                   1
sq__ft                                796
type                          Residential
sale_date    Wed May 21 00:00:00 EDT 2008
price                               68880
latitude                          38.6183
longitude                        -121.444
Name: 2, dtype: object

In [0]:
import pandas as pd
df=pd.read_csv("http://samplecsvs.s3.amazonaws.com/Sacramentorealestatetransactions.csv",nrows=4,na_values=["not available","n.a."])
df

             street        city    zip  ...  price   latitude   longitude
0      3526 HIGH ST  SACRAMENTO  95838  ...  59222  38.631913 -121.434879
1       51 OMAHA CT  SACRAMENTO  95823  ...  68212  38.478902 -121.431028
2    2796 BRANCH ST  SACRAMENTO  95815  ...  68880  38.618305 -121.443839
3  2805 JANETTE WAY  SACRAMENTO  95815  ...  69307  38.616835 -121.439146

[4 rows x 12 columns]

In [0]:
x=df.to_csv('new.csv',index=False)

In [0]:
x

In [66]:
df.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')